version = "1.1.15"

[icons]
DEFAULT = ""
"(?i)chromium" = "ï‰¨"
"geany" = "ï…œ"
"(?i)alacritty" = "ï„ "
"(?i)qtcreator" = "ï„¡"
"code" = "ï„¡"
"(?i)texworks" = "âœï¸"
"(?i)thunderbird" = "ï¯"
"github" = "ï„“"
"rust" = "î¨"
"google" = "ï† "
"private browsing" = "ïˆ›"
"firefox" = "ï‰©"
"chrome" = "ï‰¨"
"(?i)nautilus" = "ï¼"
"libreoffice calc" = "ïƒ"
"libreoffice writer" = "ïœ˜"
"libreoffice" = "ï£…"
"nvim" = "îŸ…"
"gthumb" = "ï€¾"
"menu" = "ï¡œ"
"calculator" = "ï—«"
"transmission" = "ï€™"
"videostream" = "ï˜˜"
"mpv" = "ïœª"
"music" = "ğŸ¶"
"disk usage" = "ïŸ‰"
"(?i)steam" = "ï„›"


[exclude]
"(?i)fcitx" = ".*"
aProgram = "^$"
"" = "^$"
"(?i)TestApp" = ""
"[Ss]team" = "^(Friends List.*)?$"

[format]
max_clients = 1
dedup = true
dedup_inactive_fullscreen = true
delim = ""
workspace = "{id}:{delim}{clients}"
workspace_empty = "{id}"
client = "{icon}"
client_fullscreen = "[{icon}]"
client_active = "{icon}"
client_dup = "{icon}"
client_dup_active = "{icon}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
