version = "1.1.16"

[class]
rust = "î¨"
github = "ï„“"
"(?i)qtcreator" = "ï„¡"
"libreoffice writer" = "ïœ˜"
nvim = "îŸ…"
menu = "ï¡œ"
calculator = "ï—«"
music = "ğŸ¶"
"(?i)steam" = "ï„›"
videostream = "ï˜˜"
"libreoffice calc" = "ïƒ"
gthumb = "ï€¾"
libreoffice = "ï£…"
google = "ï† "
"disk usage" = "ïŸ‰"
code = "ï„¡"
firefox = "ï‰©"
chrome = "ï‰¨"
"(?i)nautilus" = "ï¼"
transmission = "ï€™"
"(?i)chromium" = "ï‰¨"
mpv = "ïœª"
geany = "ï…œ"
"(?i)texworks" = "âœï¸"
"(?i)alacritty" = "ï„ "
DEFAULT = ""
"(?i)thunderbird" = "ï¯"
"private browsing" = "ïˆ›"

[class_active]

[initial_class]

[initial_class_active]

[workspaces_name]

[title_in_class]

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"(?i)fcitx" = ".*"
aProgram = "^$"
"" = "^$"
"(?i)TestApp" = ""
"[Ss]team" = "^(Friends List.*)?$"

[format]
max_clients = 1
dedup = true
dedup_inactive_fullscreen = true
delim = ""
workspace = "{id}:{delim}{clients}"
workspace_empty = "{id}"
client = "{icon}"
client_fullscreen = "[{icon}]"
client_active = "{icon}"
client_dup = "{icon}"
client_dup_active = "{icon}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
