# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.
"chromium" = "ï‰¨"
"geany" = "ï…œ"
"alacritty" = "ï„ "
"qt creator" = "ï„¡"
"code" = "ï„¡"
"texworks" = "âœï¸"
"github" = "ï„“"
"rust" = "î¨"
"google" = "ï† "
"private browsing" = "ïˆ›"
"firefox" = "ï‰©"
"chrome" = "ï‰¨"
"nautilus" = "ï¼"
"libreoffice calc" = "ïƒ"
"libreoffice writer" = "ïœ˜"
"libreoffice" = "ï£…"
"nvim" = "îŸ…"
"gthumb" = "ï€¾"
"menu" = "ï¡œ"
"calculator" = "ï—«"
"transmission" = "ï€™"
"videostream" = "ï˜˜"
"mpv" = "ïœª"
"music" = "ğŸ¶"
"disk usage" = "ïŸ‰"
"steam" = "ï„›"

[other]
fallback_icon = ""
deduplicate_icons = true
separator = " "
